services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\InfoHideDefaultLang\:
    resource: '../Classes/*'

  Brotkrueml\InfoHideDefaultLang\EventListener\ShowInfoAboutHideDefaultLanguage:
    tags:
      - name: event.listener
        identifier: 'info-hide-default-lang/show-info'
